import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "../lib/utils";
const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });
import { Footer } from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Vase Studio",
  description: "Generated by create next app",
  icons: { icon: "/icon.png" },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          "flex flex-col h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
